CLASS zcl_fabap_jul2025_exer05_ttl DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_amdp_marker_hdb.
    CLASS-METHODS get_data
        FOR TABLE FUNCTION ZI_FABAP_EXER05_TTL .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_FABAP_JUL2025_EXER05_TTL IMPLEMENTATION.


 METHOD get_data BY DATABASE FUNCTION
   FOR HDB LANGUAGE SQLSCRIPT
   USING /dmo/booking.
    RETURN select * from "/DMO/BOOKING"
    WHERE client = session_context('CLIENT');
  ENDMETHOD.
ENDCLASS.
